services:
  postgres:
    image: pgvector/pgvector:pg17
    container_name: semantic-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: semantic_docs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: semantic_password_2024
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    ports:
      - "5432:5432"
    volumes:
      # Dane PostgreSQL (persistent storage)
      - postgres_data:/var/lib/postgresql/data
      # Skrypty inicjalizacyjne SQL
      - ./sql/00_init_extensions.sql:/docker-entrypoint-initdb.d/00_init_extensions.sql
      - ./sql/01_create_schema.sql:/docker-entrypoint-initdb.d/01_create_schema.sql
      - ./sql/02_create_tables.sql:/docker-entrypoint-initdb.d/02_create_tables.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d semantic_docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - semantic-network

  # Kontener do uruchamiania skryptów Python
  semantic-cli:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: semantic-cli
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      - DB_HOST=postgres
      - DB_NAME=semantic_docs
      - DB_USER=postgres
      - DB_PASSWORD=semantic_password_2024
      - DB_PORT=5432
      # Konfiguracja embeddings
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_DIMENSION=384
      - CHUNK_SIZE=1000
      - CHUNK_OVERLAP=200
    volumes:
      # Montowanie lokalnych katalogów do kontenerów
      - ./scripts:/app/scripts
      # Cache dla Hugging Face datasets (updated path for non-root user)
      # - huggingface_cache:/home/appuser/.cache/huggingface
    working_dir: /app
    # Domyślnie uruchamiamy shell
    command: /bin/bash
    stdin_open: true
    tty: true
    dns:
      - 8.8.8.8
      - 8.8.4.4
      - 1.1.1.1
    networks:
      - semantic-network

networks:
  semantic-network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
  huggingface_cache:
    driver: local