version: '3.8'

services:
  # Baza danych PostgreSQL z rozszerzeniem pgvector
  db:
    image: pgvector/pgvector:pg14
    container_name: semantic-search-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: semantic_search
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Aplikacja API FastAPI
  api:
    build:
      context: .
      dockerfile: docker/Dockerfile
    container_name: semantic-search-api
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=semantic_search
      - DB_USER=postgres
      - DB_PASSWORD=password
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - EMBEDDING_MODEL=all-MiniLM-L6-v2
      - EMBEDDING_DIMENSION=384
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    command: >
      bash -c "python -m src.scripts.init_db &&
               python -m src.scripts.sample_data &&
               uvicorn src.api.main:app --host 0.0.0.0 --port 8000 --reload"

volumes:
  postgres_data: 